### ISSUE TITLE
AltSchool Logo in light mode

### ISSUE THREAD

**Issue by Omafovbe** [Oluwasetemi/altschool-opensource-names#310]
Good day,

I kinda like the idea of AltSchool logo being in the `Readme.md` file, but PR #276 which was merged sort of deleted the image from the `repo` and right now the AltSchool logo does not display in `Light Mode` while PR #239 was a fix to properly display different AltSchool logo in either Dark or Light Mode

**Comment by olakayCoder1** [comment]
I will like to fix this. let me check it out

**Comment by Oluwasetemi** [comment]
@Succynice what do you think?

**Comment by Oluwasetemi** [comment]
cc @Psalmzee @oseunabiola

**Comment by Oluwasetemi** [comment]
Has this issue been fixed? @Omafovbe if yes. you can close the issue too. Will you be interested in helping with the admin work here. The PR is growing so fast.

**Comment by Psalmzee** [comment]
Sure...will get on it now.

**Comment by Omafovbe** [comment]
@Oluwasetemi it has not been fixed. There need to exist two image files on the `repo` one to display for dark mode and another to display in light mode. right now only one image file exist which displays on dark mode. The image file AltSchool.svg shouldn't have been deleted.

Lastly, I accept the offer to help with the admin work.

**Comment by Omafovbe** [comment]
Thanks its confirmed

**Comment by Omafovbe** [comment]
Yes it has. and i would be closing the issue. Thanks
