### ISSUE TITLE
Creating a new branch before making changes should be added to the README.

### ISSUE THREAD

**Issue by zedbeit** [Oluwasetemi/altschool-opensource-names#353]
5. make changes and send PR
   - `Create a new branch`
   - Make change
   - Add file
   - Commit changes
   - Push changes (git push origin main)
   - Go to GitHub and click PR again the original (my version)

**Comment by Omafovbe** [comment]
This solution somewhat conflict with a later instruction below that says _push changes (git push origin main)_. Therefore I would advice you also include an instruction to say _git push the-current-branch_ before they can make PR on their GitHub account

**Comment by zedbeit** [comment]
Yeah It's true.

**Comment by Omafovbe** [comment]
Thanks but it seems the `Readme.md` has gotten a super upgrade from what we earlier propose and submitted. Guess you can now close this issue
