### ISSUE TITLE
clicking altschool link in the readme does not open a new tab

### ISSUE THREAD

**Issue by eddy1759** [Oluwasetemi/altschool-opensource-names#388]
I tried to click on the &copy; [AltSchool Africa](https://www.altschoolafrica.com/) link in the readme file but it's not opening on a new tab. i would like to fix this.

**Comment by Oluwasetemi** [comment]
Do you think it should open in a new tab @eddy1759 ?

**Comment by eddy1759** [comment]
Don't actually know but felt that it's better than taking the user off the original page.

**Comment by skylarng89** [comment]
I think it should open in a new tab for better user experience. The user may still want to retain the Github repo page instead of using the back button multiple times to get back to where they came from.

**Comment by Oluwasetemi** [comment]
Can @eddy1759 send in a PR for this referencing this issue in the comment under the PR.

**Comment by eddy1759** [comment]
i did that already sir

**Comment by eddy1759** [comment]
https://github.com/Oluwasetemi/altschool-opensource-names/pull/390/#issue-1337081918

here is the link

**Comment by Oluwasetemi** [comment]
I think I merged the PR but noticed no changes. Researched a little and got this [https://stackoverflow.com/a/42156438/4330745](https://stackoverflow.com/a/42156438/4330745)
<img width="734" alt="image" src="https://user-images.githubusercontent.com/10030028/184578998-7ec3c780-478c-4140-8859-b33116754d4a.png">

**Comment by eddy1759** [comment]
Thank you very much sir for the enlightenment.

**Comment by Oluwasetemi** [comment]
Awesome.
