### ISSUE TITLE
The duplicate name test is not case-sensitive

### ISSUE THREAD

**Issue by oseunabiola** [Oluwasetemi/altschool-opensource-names#738]
The duplicate name test is not case-sensitive.

Sample. Name written in different cases.

![image](https://user-images.githubusercontent.com/28025908/185376048-d62a7968-a7c3-4538-a857-d2d4269e4ef5.png)

**Comment by oluwakamiyeayan** [comment]
How do I fix. I will like to work on it.

**Comment by oseunabiola** [comment]
Resolved with PR https://github.com/Oluwasetemi/altschool-opensource-names/pull/758
