### ISSUE TITLE
Duplicate names

### ISSUE THREAD

**Issue by tobisupreme** [Oluwasetemi/altschool-opensource-names#832]
Running `node testDuplicate.js` returns duplicates

![image](https://user-images.githubusercontent.com/98078707/186889638-cda89f5a-1b26-44fe-a73e-487fdf55cb95.png)

**Comment by Oluwasetemi** [comment]
hmmm 
trouble. we can manually resolve this.

**Comment by tobisupreme** [comment]
Yes. A PR has been merged to that effect
